# permissions for end users to view globaldnszones.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: globaldnszone-viewer-role
rules:
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - globaldnszones
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - globaldnszones/status
  verbs:
  - get
