# permissions for end users to edit globaldnszones.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: globaldnszone-editor-role
rules:
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - globaldnszones
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - globaldnszones/status
  verbs:
  - get
