# permissions for end users to view globalroutediscoveries.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: globalroutediscovery-viewer-role
rules:
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - globalroutediscoveries
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - globalroutediscoveries/status
  verbs:
  - get
