# permissions for end users to edit globaldnsrecords.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: globaldnsrecord-editor-role
rules:
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - globaldnsrecords
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - globaldnsrecords/status
  verbs:
  - get
