apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: globaldnszones.redhatcop.redhat.io
spec:
  group: redhatcop.redhat.io
  names:
    kind: GlobalDNSZone
    listKind: GlobalDNSZoneList
    plural: globaldnszones
    singular: globaldnszone
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: GlobalDNSZone is the Schema for the globaldnszones API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: GlobalDNSZoneSpec defines the desired state of GlobalDNSZone
            properties:
              domain:
                pattern: (?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z0-9][a-z0-9-]{0,61}[a-z0-9]
                type: string
              provider:
                description: ProviderConfig configures kind and access to the DNS
                  Zone. Exactly one of its members must be set.
                properties:
                  externalDNS:
                    description: ExternalDNSProviderConfig contains configuration
                      on how configure the external DNS provider
                    properties:
                      annotations:
                        additionalProperties:
                          type: string
                        description: Annotations is a map of annotations to be added
                          to the created DNSEndpoint records.
                        type: object
                    type: object
                  route53:
                    description: Route53ProviderConfig contains configuration on how
                      to access the route53 API
                    properties:
                      credentialsSecretRef:
                        description: CredentialsSecretRef is a reference to a secret
                          containing the credentials to access the AWS API //TODO
                          (content and needed permissions) expected secret keys are
                          "aws_access_key_id" and "aws_secret_access_key"
                        properties:
                          name:
                            type: string
                          namespace:
                            type: string
                        required:
                        - name
                        - namespace
                        type: object
                      zoneID:
                        description: ZoneID is the AWS route53 zone ID.
                        type: string
                    required:
                    - credentialsSecretRef
                    - zoneID
                    type: object
                type: object
            required:
            - domain
            - provider
            type: object
          status:
            description: GlobalDNSZoneStatus defines the observed state of GlobalDNSZone
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
