---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: global-load-balancer-operator
rules:
  - apiGroups:
    - redhatcop.redhat.io
    resources:
    - globaldnszones
    - globaldnszones/finalizers
    - globaldnszones/status
    - globaldnsrecords
    - globaldnsrecords/finalizers
    - globaldnsrecords/status    
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - ""
    resources:
    - secrets
    verbs:
    - get
    - list
    - watch                 
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: egressip-ipam-operator
rules:
# leader election   
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  verbs:
  - "*"  
#Metrics  
- apiGroups:
  - ""
  resources:
  - services
  - services/finalizers
  verbs:
  - "*"
#Metrics  
- apiGroups:
  - "apps"
  resources:
  - replicasets
  - deployments
  verbs: 
  - "get"
  - "list"
# Metrics  
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - "get"
  - "create"
# Metrics  
- apiGroups:
  - apps
  resources:
  - deployments/finalizers
  resourceNames:
  - global-load-balancer-operator
  verbs:
  - "update"  
